### ISSUE TITLE
$interaction->member is always NULL

### ISSUE THREAD

**Issue by Swift42** [discord-php/DiscordPHP-Slash#18]
Hello,

first of all: Thanks for this useful library.

When using:
```
$client->registerCommand('command', function (Interaction $interaction, Choices $choices) use ($discord) 
{
  [...]
}
```

all information is present in $interaction, but the member field is always NULL.

Maybe I'm doing something wrong, but I can fix this by modifying Parts/Interaction.php from ...
```
 private function member()
 {
        return $this->guild->members->get('id', $this->attributes['member']['user']['id']);
 }
```
to simply:
```
 private function member()
 {
        return $this->attributes['member'];
 }
```

**Comment by SQKo** [comment]
The returned value is actually supposed to be the Member Part from [DiscordPHP](https://github.com/discord-php/DiscordPHP) separated from this library, the problem is the Member of the specified id is and not yet cached from DiscordPHP. While the DiscordPHP-Slash (this library) does receive a Member object from interaction data.

Doing your suggested fix,
```php
 private function member()
 {
        return $this->attributes['member'];
 }
```
does indeed return a Member object, but that is just a stdObject of partial member data. not the full [Member object](https://github.com/discord-php/DiscordPHP/blob/master/src/Discord/Parts/User/Member.php)

Ideally the fix is to integrate Slash feature from this library into DiscordPHP, which is current on the work https://github.com/discord-php/DiscordPHP/pull/597 so the Member data will be automatically cached

The temporary fix right now would be enabling GUILD_MEMBERS intent and enable `loadAllMembers` in DiscordPHP options so the member will be present in cache

**Comment by Swift42** [comment]
Thanks for the answer.
Yes, I'm using Slash with Discord-PHP and in the docs I can read:

> If you are using DiscordPHP Version 6 or greater, you need to enable the GUILD_MEMBERS intent as well as the loadAllMembers option.

This seems to be the culprit (as you said, too). 
But this would need extended authentication (with "redirect URI") and I really don't need the full member data, only the ID, so for a quick fix I would suggest a second object named "member_raw", which contains the partial member data stdObject:

```
class Interaction extends Part
{
    protected $fillable = ['id', 'type', 'data', 'guild_id', 'channel_id', 'member', 'token', 'version', 'guild', 'channel', 'member_raw'];
[...]

private function member_raw()
{
        return $this->attributes['member'];
}
```

This works perfectly and and for me it is completely sufficient.

**Comment by SQKo** [comment]
I could be wrong but you maybe can do it already with this:
```php
$interaction_raw = $interaction->getAttributes();

// Now you can get:
$interaction_raw['member']['id'];
```

**Comment by Swift42** [comment]
You are right! This works and I don't need to modify the lib.
Thanks for your help.
