### ISSUE TITLE
DM slash commands

### ISSUE THREAD

**Issue by davidcole1340** [discord-php/DiscordPHP-Slash#7]
https://github.com/discord/discord-api-docs/pull/2568

**Comment by SQKo** [comment]
DM slash commands is already implemented from Global command when the user shares same guild with the bot.

**Comment by Corin123555** [comment]
> DM slash commands is already implemented from Global command when the user shares same guild with the bot.

This isn't the case it seems, when accessing the `Interaction` part, unfortunately it also calls the `guild`, `channel` and `member` methods.

But as this is in a DM, none of the data required for these to actually initialise is accessible and as a result it'll cause a fatal error.

**Comment by SQKo** [comment]
> > DM slash commands is already implemented from Global command when the user shares same guild with the bot.
> 
> This isn't the case it seems, when accessing the `Interaction` part, unfortunately it also calls the `guild`, `channel` and `member` methods.
> 
> Unfortunately none of these are accessible and as a result it'll cause a fatal error.

That is not true, I've made one global command and used it on DM, works good.

You shouldn't call the `guild` `channel` and `member` methods in the `Interaction`


```php
$client->registerCommand('my_cool_command', function (Interaction $interaction, Choices $choices) use ($discord) {
    if (!isset($interaction->guild_id)) {
        // This is DM command because guild_id is null
    }
});
```

**Comment by Corin123555** [comment]
Yeah that was my problem just noticed, logger accesses them all before it actually processes the command itself.
I was using `$interaction->member` instead of `$interaction->user` for user info.

The thing that threw me off was trying to var_dump the `Interaction` just to see the contents would always cause it to fatal.
Might it better to do do a check first to see if `members` etc is actually set before calling otherwise just return null?
